import type { Section } from "./types";

const PAIRS: Array<[RegExp, string]> = [
  [/\bSalman and Rayan\b/g, "Sarah and Noura"],
  [/\bSalman & Rayan\b/g, "Sarah & Noura"],
  [/\bAbdullah and Tariq\b/g, "Lulwah and Reem"],
  [/\bHamza and Ziyad\b/g, "Leen and Hind"],
  [/\bNawaf and Sultan\b/g, "Shahad and Jana"],
  [/\bSaud and Faisal\b/g, "Reem and Jouri"],
  [/\bSaud & Fahad\b/g, "Reem & Rowan"],
  [/\bSalman\b/g, "Sarah"],
  [/\bRayan\b/g, "Noura"],
  [/\bAbdullah\b/g, "Lulwah"],
  [/\bTariq\b/g, "Reem"],
  [/\bHamza\b/g, "Leen"],
  [/\bZiyad\b/g, "Hind"],
  [/\bNawaf\b/g, "Shahad"],
  [/\bSultan\b/g, "Jana"],
  [/\bSaud\b/g, "Reem"],
  [/\bFaisal\b/g, "Jouri"],
  [/\bOmar\b/g, "Maryam"],
  [/\bKhaled\b/g, "Fatima"],
  [/\bKhalid\b/g, "Fatima"],
  [/\bAhmed\b/g, "Yasmin"],
  [/\bFaris\b/g, "Renad"],
  [/\bBadr\b/g, "Dima"],
  [/\bRakan\b/g, "Tala"],
  [/\bYousef\b/g, "Hanaa"],
  [/\bTamim\b/g, "Joud"],
  [/\bAli\b/g, "Dana"],
  [/\bFahad\b/g, "Rowan"],
  [/\bNasser\b/g, "Yara"],
  [/\bIbrahim\b/g, "Lama"],
  [/\bHussain\b/g, "Ghala"],
  [/\bMajed\b/g, "Amira"],
  [/\bWaleed\b/g, "Ghala"],
  [/سلمان وريان/g, "سارة ونورة"],
  [/عبدالله وطارق/g, "لولوة وريم"],
  [/حمزة وزياد/g, "لين وهند"],
  [/نواف وسلطان/g, "شهد وجنى"],
  [/سعود وفيصل/g, "ريم وجوري"],
  [/سعود وفهد/g, "ريم وروان"],
  [/سلمان/g, "سارة"],
  [/ريان/g, "نورة"],
  [/عبدالله/g, "لولوة"],
  [/طارق/g, "ريم"],
  [/حمزة/g, "لين"],
  [/زياد/g, "هند"],
  [/نواف/g, "شهد"],
  [/سلطان/g, "جنى"],
  [/سعود/g, "ريم"],
  [/فيصل/g, "جوري"],
  [/عمر/g, "مريم"],
  [/خالد/g, "فاطمة"],
  [/أحمد/g, "ياسمين"],
  [/فارس/g, "ريناد"],
  [/بدر/g, "ديما"],
  [/راكان/g, "تالا"],
  [/يوسف/g, "هناء"],
  [/تميم/g, "جود"],
  [/علي/g, "دانة"],
  [/فهد/g, "روان"],
  [/ناصر/g, "يارا"],
  [/إبراهيم/g, "لمى"],
  [/حسين/g, "غلا"],
  [/ماجد/g, "أميرة"],
  [/وليد/g, "غلا"],
  [/\bbrotherhood\b/gi, "sisterhood"],
  [/\bbrothers\b/gi, "sisters"],
  [/\bbrother\b/gi, "sister"],
  [/\bhimself\b/gi, "herself"],
  [/\bhis classmates\b/gi, "her classmates"],
  [/\bhis peers\b/gi, "her peers"],
  [/\bhis friends\b/gi, "her friends"],
  [/\bhis friend\b/gi, "her friend"],
  [/أخوته/g, "أخواتها"],
  [/زملائه/g, "زميلاتها"],
  [/زميله/g, "زميلتها"],
  [/الطالب/g, "الطالبة"],
  [/الطلاب/g, "الطالبات"],
  [/الفارس/g, "الفارسة"],
  [/فرسان/g, "فارسات"],
  [/بطل/g, "بطلة"],
  [/أبطال/g, "بطلات"],
  [/\bchampion\b/gi, "champion"],
  [/\bboy\b/gi, "girl"],
  [/\bBoys\b/g, "Girls"],
];

export function adapt(text: string, section: Section): string {
  if (!text || section !== "girls") return text;
  let out = text;
  for (const [re, to] of PAIRS) out = out.replace(re, to);
  return out;
}
